
Run('C:\\Users\\stefa\\OneDrive\\Desktop\\test.pmr')
WinWaitActive('PyMacroRecord')
Send('^l')
Sleep(500)
Send('startChrome')
Sleep(500)
Send('{Enter}')
Sleep(500)
Click(87, 105, 'Left')
Sleep(10000)
WinClose('PyMacroRecord')
