from enum import Enum
import json

class CountryCode(Enum):
    AUSTRIA = "+43"
    BELGIUM = "+32"
    CROATIA = "+385"
    CYPRUS = "+357"
    CZECH = "+420"
    DENMARK = "+45"
    ENGLAND = "+44"
    FINLAND = "+358"
    FRANCE = "+33"
    GERMANY = "+49"
    GREECE = "+30"
    HUNGARY = "+36"
    IRELAND = "+353"
    ITALY = "+39"
    LATVIA = "+371"
    LITHUANIA = "+370"
    NETHERLANDS = "+31"
    NORWAY = "+47"
    POLAND = "+48"
    ROMANIA = "+40"
    SLOVAKIA = "+421"
    SLOVENIA = "+386"
    SPAIN = "+34"
    SERBIA = "+381"
    SWEDEN = "+46"
    SWITZERLAND = "+41"


class Country(Enum):
    AUSTRIA = "austria"
    BELGIUM = "belgium"
    CROATIA = "croatia"
    CYPRUS = "cyprus"
    CZECH = "czech"
    DENMARK = "denmark"
    ENGLAND = "england"
    FINLAND = "finland"
    FRANCE = "france"
    GERMANY = "germany"
    GREECE = "greece"
    HUNGARY = "hungary"
    IRELAND = "ireland"
    ITALY = "italy"
    LATVIA = "latvia"
    LITHUANIA = "lithuania"
    NETHERLANDS = "netherlands"
    NORWAY = "norway"
    POLAND = "poland"
    ROMANIA = "romania"
    SLOVAKIA = "slovakia"
    SLOVENIA = "slovenia"
    SPAIN = "spain"
    SERBIA = "serbia"
    SWEDEN = "sweden"
    SWITZERLAND = "switzerland"


