from enum import Enum
import json

class CountryCode(Enum):
    AUSTRIA = "+43"
    BELGIUM = "+32"
    CROATIA = "+385"
    CYPRUS = "+357"
    CZECH = "+420"
    DENMARK = "+45"
    ENGLAND = "+44"
    FINLAND = "+358"
    FRANCE = "+33"
    GERMANY = "+49"
    GREECE = "+30"
    HUNGARY = "+36"
    IRELAND = "+353"
    ITALY = "+39"
    LATVIA = "+371"
    LITHUANIA = "+370"
    NETHERLANDS = "+31"
    NORWAY = "+47"
    POLAND = "+48"
    ROMANIA = "+40"
    SLOVAKIA = "+421"
    SLOVENIA = "+386"
    SPAIN = "+34"
    SERBIA = "+381"
    SWEDEN = "+46"
    SWITZERLAND = "+41"

class Language(Enum):
    AUSTRIA = "de-AT"
    BELGIUM = "nl-BE"
    CROATIA = "hr-HR"
    CYPRUS = "el-CY"
    CZECH = "cs-CZ"
    DENMARK = "da-DK"
    ENGLAND = "en-GB"
    FINLAND = "fi-FI"
    FRANCE = "fr-FR"
    GERMANY = "de-DE"
    GREECE = "el-GR"
    HUNGARY = "hu-HU"
    IRELAND = "en-IE"
    ITALY = "it-IT"
    LATVIA = "lv-LV"
    LITHUANIA = "lt-LT"
    NETHERLANDS = "nl-NL"
    NORWAY = "no-NO"
    POLAND = "pl-PL"
    ROMANIA = "ro-RO"
    SLOVAKIA = "sk-SK"
    SLOVENIA = "sl-SI"
    SPAIN = "es-ES"
    SERBIA = "sr-RS"
    SWEDEN = "sv-SE"
    SWITZERLAND = "de-CH"


class Country(Enum):
    AUSTRIA = "austria"
    BELGIUM = "belgium"
    CROATIA = "croatia"
    CYPRUS = "cyprus"
    CZECH = "czech"
    DENMARK = "denmark"
    ENGLAND = "england"
    FINLAND = "finland"
    FRANCE = "france"
    GERMANY = "germany"
    GREECE = "greece"
    HUNGARY = "hungary"
    IRELAND = "ireland"
    ITALY = "italy"
    LATVIA = "latvia"
    LITHUANIA = "lithuania"
    NETHERLANDS = "netherlands"
    NORWAY = "norway"
    POLAND = "poland"
    ROMANIA = "romania"
    SLOVAKIA = "slovakia"
    SLOVENIA = "slovenia"
    SPAIN = "spain"
    SERBIA = "serbia"
    SWEDEN = "sweden"
    SWITZERLAND = "switzerland"



class CountryTimezone(Enum):
    AUSTRIA = "Europe/Vienna"
    BELGIUM = "Europe/Brussels"
    CROATIA = "Europe/Zagreb"
    CYPRUS = "Asia/Nicosia"  # Not Europe/, but correct for Cyprus
    CZECH = "Europe/Prague"
    DENMARK = "Europe/Copenhagen"
    ENGLAND = "Europe/London"
    FINLAND = "Europe/Helsinki"
    FRANCE = "Europe/Paris"
    GERMANY = "Europe/Berlin"
    GREECE = "Europe/Athens"
    HUNGARY = "Europe/Budapest"
    IRELAND = "Europe/Dublin"
    ITALY = "Europe/Rome"
    LATVIA = "Europe/Riga"
    LITHUANIA = "Europe/Vilnius"
    NETHERLANDS = "Europe/Amsterdam"
    NORWAY = "Europe/Oslo"
    POLAND = "Europe/Warsaw"
    ROMANIA = "Europe/Bucharest"
    SLOVAKIA = "Europe/Bratislava"
    SLOVENIA = "Europe/Ljubljana"
    SPAIN = "Europe/Madrid"
    SERBIA = "Europe/Belgrade"
    SWEDEN = "Europe/Stockholm"
    SWITZERLAND = "Europe/Zurich"

